version: 2

models:
  - name: int_progress_card
    description: 'In this table add some columns that are relevant to this table, they are as:'
    columns:
      - name: stud_contact_no
        description: 'Contact number of student'
      - name: stud_email
        description: 'Email address of student' 
      - name: stud_city
        description: 'City of student where they are live'
      - name: stud_preferred_language
        description: 'Preferred language of student'
      - name: stud_registered_date
        description: 'date of registration when student registered in geeta samagam'
        
