
version: 2

models:
  - name: stg_students
    description: 'This table contains the information of students like their name, gender, email etc.'
    columns:
      - name: student_id
        description: 'This is a primary key(unique identifier for each row) in this table.'
        tests:
          - not_null
          - unique
      - name: name
        description: 'Name of Student.'
      - name: gender
        description: 'Gender of student.'
        tests:
          - accepted_values:
              values: ['Female', 'Male', 'Unknown']
      - name: age 
        description: 'Age of student.'
        tests:
          - value_between:
              min_value: 13
              max_value: 75
      - name: contact_no
        description: 'Contact number or Mobile number of student.'
      - name: email
        description: 'Email address of student.'
      - name: email_domain
        description: "Domain of student's email address such as @gmail.com, @yahoo.com etc."
        tests:
          - accepted_values:
              values: ['@rediffmail.com', '@gmail.com', '@outlook.com', '@yahoo.com']
      - name: city
        description: 'City of students where they live.'
      - name: state
        description: 'State of students where they belongs like Uttar Pradesh, Madhya Pradesh, Bihar etc.'
      - name: preferred_language
        description: 'preferred language by student like Hinid, English etc.'
      - name: connect_with
        description: 'Name of the counsellor who enrolled student.'
      - name: registered_date
        description: 'Date of enrollment when student enrolled first time into Geeta Samagam.'
  
  - name: stg_progress_card
    description: "This is a student report card where we can see their attendace, posts, exam's result etc."
    columns:
      - name: progress_id
        description: 'This is a primary(unique identifier for each row) in this table.'
        tests:
          - not_null
          - unique
      - name: student_id
        description: 'Unique id for each student.'
      - name: session_attendance_last_3_months
        description: 'Attendance of student to attend sessions in last 3 months in the form of percentage(%)'
        tests:
          - value_between:
              min_value: 0
              max_value: 100
      - name: posts_on_gita_community
        description: 'Number of posts or reflection written by student.'
        tests:
          - is_positive
      - name: enrolled_for_august
        description: 'This column simply describes that student has already enrolled for august month or not.'
        tests:
          - accepted_values:
              values: [true, false]
              quote: false
      - name: duration_continuous_enrollment_live_session
        description: 'This column simply describes how long student has been enrolling continuously for live session.'
        tests:
          - is_positive
      - name: last_gita_exam_percentile
        description: 'The percentile of last gita exam scored by student.'
        tests:
          - value_between:
              min_value: 0
              max_value: 100
      - name: exam_attendance
        description: 'This column simply describes how frequently student interacts with exam in percentage(%)'
        tests:
          - value_between:
              min_value: 0
              max_value: 100
      - name: total_duration_enrollment_live_session
        description: 'This column simply describes how long student has been enrolling for live session.'
        tests:
          - is_positive
      - name: total_view_duration_session_recording_last_30_days
        description: 'This column simply describes how many hours of recording wathched by student.'
        tests:
          - is_positive
      - name: calls_from_foundation_picked_last_3_months
        description: 'This column simply describes how frequently student recieves the phone of foundation.'
        tests:
          - value_between:
              min_value: 0
              max_value: 100
      - name: invite_student
        description: 'This column simply describes how many invitation link sent by student to join geeta community.'
        tests:
          - is_positive
      - name: student_added_in_geeta_samagam
        description: 'This column simply describes how many students added by students into geeta samagam or geeta community.'
        tests:
          - is_positive
      - name: active_added_student
        description: 'This column simply describes how many students are active on geeta community those added by student.'
        tests:
          - is_positive
        


    