
version: 2

snapshots:
  - name: dim_students_snapshot
    description: Snapshot of student data to track changes to contact_no, email and city over time.
    columns:
      - name: student_id
        description: Primary key for students
        tests:
          - unique
          - not_null
      - name: contact_no
        description: Latest contact number
        tests:
          - not_null
      - name: email
        description: Latest email address
        tests:
          - not_null
          - unique
      - name: city
        description: Latest city of student 
    
